language: node_js
dist: trusty
sudo: required
node_js:
 - "9.5.0"

before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3 # give xvfb some time to start

addons:
  chrome: stable